sudo: required

env:
  global:
  - REPO=bhavikk/guide-aws-swarm
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: yJx+2etbe6+OvcBnmio/mvBhkRaGRM1/RbzALqU/uF+p1Hi4rozupf0PrO/zscxKD+72mK7YoCRIXOo/xetUA9LbGFGfVtBLbo53qxsmJ6bZc5XFrwxwYXPyvKnGZ/dBbP2e886pb8dthIqtepbVPAoDlkpDpw/MWpKwE4InvSPr9m4vwQhEUEsvqKo9KdImfsSOipdKAN/ll1lKCtY3oJjHO/y3ZC6WRB4cCyo3xP/g9L4mylHMXpVTKTDHzsKhnBBQUM9bmgb4t4jXgGhI3mtFhltOLX7M/kDp/onSuhV9CiX44Ne1Nw9REAxb3dtMJD88vkrFk8TRJAuKEty48zGcV0IPhP0lt8r8EhGzS8zCI9PzrSxd1KuIDno7aZVBMWCEK+xCKHAi311hKvZjObKLXBNQUF7x+X/VPHDxiFy7d9BCn4600Lhn4j9Jt5zPW/O97Kj3og8YTdgfhLoX7Nf+sAe4xtbd58tAZWBQ4g5ACng+XmtObaw1fSSmSYvSjqUnNqpWagUy64CEKFw4XqJxCC+stBMFEVPnxKJQzvlTqRfK01W4aeBYMrBBcUCt9flydLwRg5thvcaJBLqCHCpygUi2JFWr33vyxNXPO/jt8igKyNvRHlGjj9z5KlkWj1BvQ5AJFWW9H4klQ9o8FoToP3sOozAVR+6MowO9dqY=
  - secure: XmaG2lw716SoQ0oOHmTArsvG+dSzZZ6kbPN5866SugASavL7ioH1ya71Ha0NRanxTtETq/Nrw9iNpX2bqDiwlTAmAzrMiI1Uhd1YRD8bbzXj1s/cYnxHDGAgxwo/sJ9jBoMAjMTJDYU8mSZ/GrP4slIn7KPKUvphvcNRHqWJ3CXoOu25+FetCkcvqwlrMLsdrToCODQJF8jwLfUggnaqACqLBRFl7wrCjcyaEPpIqbutC/mkT5haG+2l1on/qUzU+j2F7885glMVwOgiP1Bn1wQmp7wDmCqQkBU8/mAEHRos2k8zKGlUwzPBlvpdROIo5y2tNObT78sJAk4CwLc6jFtr3vYUZknHB9r+9d/C36ynuRBi18DHLUGx0/MD5KE/g4RmEiHbh6+mJeF1JqTmp4pRM0Sbf8u97z3ERIaNFC8jjKDfDc5Bp2/sJ+Xlo5K3+REBkX5TpDXIgu5l/oxzhAEbI6RB1kTmpS4Z6nbXqy2f9ZN/Ej0VR7Csm4FsY4rl90iXJ/FazFomESL39a3eJkWzboeqxYNwEchBUOeeLojpZcZKWYnDl9L7Pt35TnvsyiXdlpNmx9TOqdFshEfGMOij0xALGkdBE0+oxZlfOdNPGvjCbRK2LZwM0NwcKCLYWQZyrv0B7qg2D3OJ2hmDZq1fBgKr/VY2BTRzs/1bPq4=  

services:
- docker

before_script:
- export TZ=Pacific/Auckland
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`

branches:
  only:
  - master

script:
- docker build -t $REPO:$TAG -f Dockerfile .

after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
